# Generated by Django 4.1 on 2022-08-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism Familiya')),
                ('start_date', models.DateField(verbose_name='Boshlanish sana')),
                ('end_date', models.DateField(verbose_name='Tugash sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Sertifikat nusxasi')),
                ('certificate_id', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Certificate ID')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
